use public_housing;
WITH CTE AS (
  SELECT
    PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
    STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS MR_INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST,
    LAG(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) AS SECOND_MR_INSPECTION_DATE,
    LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) AS SECOND_MR_INSPECTION_COST,
    ROW_NUMBER() OVER(PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') DESC) AS rn
  FROM public_housing_inspection_data
),
CostIncrease AS (
  SELECT
    PHA_NAME,
   MR_INSPECTION_DATE,
    MR_INSPECTION_COST,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    MR_INSPECTION_COST - SECOND_MR_INSPECTION_COST AS CHANGE_IN_COST,
    ((MR_INSPECTION_COST - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST) * 100 AS PERCENT_CHANGE_IN_COST
  FROM CTE
  WHERE rn = 1 AND MR_INSPECTION_COST > SECOND_MR_INSPECTION_COST
)
SELECT
  PHA_NAME,
  MR_INSPECTION_DATE,
  MR_INSPECTION_COST,
  SECOND_MR_INSPECTION_DATE,
  SECOND_MR_INSPECTION_COST,
  CHANGE_IN_COST,
  PERCENT_CHANGE_IN_COST
FROM CostIncrease;