USE assignment3project;

WITH InspectionData AS (
    SELECT
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS AS INSPECTION_COST,
        LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') DESC) AS NEXT_INSPECTION_COST,
        LEAD(INSPECTION_DATE) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') DESC) AS NEXT_INSPECTION_DATE
    FROM
        public_housing_inspection_data
    WHERE
        INSPECTION_DATE IS NOT NULL AND
        COST_OF_INSPECTION_IN_DOLLARS IS NOT NULL
),
FilteredData AS (
    SELECT
        PHA_NAME,
        INSPECTION_DATE AS MR_INSPECTION_DATE,
        INSPECTION_COST AS MR_INSPECTION_COST,
        NEXT_INSPECTION_DATE AS SECOND_MR_INSPECTION_DATE,
        NEXT_INSPECTION_COST AS SECOND_MR_INSPECTION_COST,
        (INSPECTION_COST - NEXT_INSPECTION_COST) AS CHANGE_IN_COST,
        ((INSPECTION_COST - NEXT_INSPECTION_COST) / NEXT_INSPECTION_COST * 100) AS PERCENT_CHANGE_IN_COST
    FROM
        InspectionData
    WHERE
        NEXT_INSPECTION_COST IS NOT NULL AND
        INSPECTION_COST > NEXT_INSPECTION_COST
),
RankedData AS (
    SELECT
        *,
        ROW_NUMBER() OVER (PARTITION BY PHA_NAME ORDER BY STR_TO_DATE(MR_INSPECTION_DATE, '%m/%d/%Y') DESC) AS rn
    FROM
        FilteredData
)
SELECT
    PHA_NAME,
    MR_INSPECTION_DATE,
    MR_INSPECTION_COST,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    CHANGE_IN_COST,
    PERCENT_CHANGE_IN_COST
FROM
    RankedData
WHERE
    rn = 1;
