DROP DATABASE IF EXISTS public_housing_inspection;
CREATE DATABASE IF NOT EXISTS public_housing_inspection;
USE public_housing_inspection;

--- Create Table
CREATE TABLE public_housing_inspection (
    INSPECTION_ID INT PRIMARY KEY,
    PUBLIC_HOUSING_AGENCY_NAME VARCHAR(255),
    COST_OF_INSPECTION_IN_DOLLARS DECIMAL(10, 2),
    INSPECTED_DEVELOPMENT_NAME VARCHAR(255),
    INSPECTED_DEVELOPMENT_ADDRESS VARCHAR(255),
    INSPECTED_DEVELOPMENT_CITY VARCHAR(100),
    INSPECTED_DEVELOPMENT_STATE CHAR(2),
    INSPECTION_DATE DATE,
    INSPECTION_SCORE INT
);

SET GLOBAL local_infile = 1;

--- Load Data into the Table
LOAD DATA LOCAL INFILE 'C:/Users/USER/Desktop/NEU/2024-Fall/ALY6030-Data Warehousing and SQL/M4/public_housing_inspection_data.csv'
INTO TABLE public_housing_inspection
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(INSPECTION_ID, PUBLIC_HOUSING_AGENCY_NAME, COST_OF_INSPECTION_IN_DOLLARS, 
 INSPECTED_DEVELOPMENT_NAME, INSPECTED_DEVELOPMENT_ADDRESS, 
 INSPECTED_DEVELOPMENT_CITY, INSPECTED_DEVELOPMENT_STATE, 
 @INSPECTION_DATE, INSPECTION_SCORE)
SET INSPECTION_DATE = STR_TO_DATE(@INSPECTION_DATE, '%m/%d/%Y');

--- Q5
WITH InspectionRanked AS (
    SELECT PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
           INSPECTION_DATE,
           COST_OF_INSPECTION_IN_DOLLARS AS INSPECTION_COST,
           LAG(INSPECTION_DATE) OVER (
               PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE) AS SECOND_MR_INSPECTION_DATE,
           LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (
               PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE) AS SECOND_MR_INSPECTION_COST,
           ROW_NUMBER() OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE DESC) AS RN
    FROM public_housing_inspection
)
SELECT 
    PHA_NAME,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    INSPECTION_DATE AS MR_INSPECTION_DATE,
    INSPECTION_COST AS MR_INSPECTION_COST,
    (INSPECTION_COST - SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
    ROUND((INSPECTION_COST - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST * 100, 2) AS PERCENT_CHANGE_IN_COST
FROM InspectionRanked
WHERE SECOND_MR_INSPECTION_COST IS NOT NULL
AND INSPECTION_COST > SECOND_MR_INSPECTION_COST
AND RN = 1;
