--  the inspection date is stored as TEXT, we convert it to DATE using STR_TO_DATE function
WITH RankedInspections AS (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS INSPECTION_DATE,  -- Convert the date format
        COST_OF_INSPECTION_IN_DOLLARS,
        LAG(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') DESC) AS SECOND_MR_INSPECTION_DATE,
        LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') DESC) AS SECOND_MR_INSPECTION_COST
    FROM 
        public_housing_inspection_data
    WHERE 
        STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') IS NOT NULL -- Ensure that dates are valid
)
-- Select final result by filtering for increased costs and excluding PHAs with only one inspection
SELECT 
    PHA_NAME,
    INSPECTION_DATE AS MR_INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    COST_OF_INSPECTION_IN_DOLLARS - SECOND_MR_INSPECTION_COST AS CHANGE_IN_COST,
    (COST_OF_INSPECTION_IN_DOLLARS - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST * 100 AS PERCENT_CHANGE_IN_COST
FROM 
    RankedInspections
WHERE 
    SECOND_MR_INSPECTION_DATE IS NOT NULL   -- Filter out PHAs with only one inspection
    AND (COST_OF_INSPECTION_IN_DOLLARS - SECOND_MR_INSPECTION_COST) > 0 -- Filter for cost increase
ORDER BY 
    PHA_NAME;
