
USE housing_inspection;
SET SQL_SAFE_UPDATES = 0;

#Converting Text into date
ALTER TABLE Publishing_House
ADD COLUMN FORMATTED_INSPECTION_DATE DATE;

UPDATE Publishing_House
SET FORMATTED_INSPECTION_DATE = STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y');

SELECT INSPECTION_DATE, FORMATTED_INSPECTION_DATE 
FROM Publishing_House 
LIMIT 5;


#Step 1: Calculate the change in inspection cost between the most recent and second most recent inspections
-- Use LEAD() function to get the next inspection date and cost within the same Public Housing Agency (PHA)
-- Partition by PHA name and order by the formatted inspection date in descending order
SELECT 
    PUBLIC_HOUSING_AGENCY_NAME,
    FORMATTED_INSPECTION_DATE AS SECOND_MR_INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS AS SECOND_MR_INSPECTION_COST,
    LEAD(FORMATTED_INSPECTION_DATE) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) AS MR_INSPECTION_DATE,
    LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) AS MR_INSPECTION_COST,
    (LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) - COST_OF_INSPECTION_IN_DOLLARS) AS CHANGE_IN_COST,
    ((LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) - COST_OF_INSPECTION_IN_DOLLARS) / COST_OF_INSPECTION_IN_DOLLARS) * 100 AS PERCENT_CHANGE_IN_COST
FROM 
    Publishing_House;


#Step 2: Filter the results to include only records where the inspection cost has increased
-- Display only those PHAs that saw a cost increase between the two most recent inspections

SELECT PUBLIC_HOUSING_AGENCY_NAME, 
       MR_INSPECTION_DATE, 
       MR_INSPECTION_COST, 
       SECOND_MR_INSPECTION_DATE, 
       SECOND_MR_INSPECTION_COST, 
       CHANGE_IN_COST, 
       PERCENT_CHANGE_IN_COST
FROM (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME,
        FORMATTED_INSPECTION_DATE AS SECOND_MR_INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS AS SECOND_MR_INSPECTION_COST,
        LEAD(FORMATTED_INSPECTION_DATE) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) AS MR_INSPECTION_DATE,
        LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) AS MR_INSPECTION_COST,
        (LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) - COST_OF_INSPECTION_IN_DOLLARS) AS CHANGE_IN_COST,
        ((LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) - COST_OF_INSPECTION_IN_DOLLARS) / COST_OF_INSPECTION_IN_DOLLARS) * 100 AS PERCENT_CHANGE_IN_COST
    FROM 
        Publishing_House
) AS cost_changes
WHERE CHANGE_IN_COST > 0;

CREATE TABLE Increased_Inspection_Costs AS
SELECT DISTINCT 
    PUBLIC_HOUSING_AGENCY_NAME, 
    MR_INSPECTION_DATE, 
    MR_INSPECTION_COST, 
    SECOND_MR_INSPECTION_DATE, 
    SECOND_MR_INSPECTION_COST, 
    CHANGE_IN_COST, 
    PERCENT_CHANGE_IN_COST
FROM (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME,
        FORMATTED_INSPECTION_DATE AS SECOND_MR_INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS AS SECOND_MR_INSPECTION_COST,
        LEAD(FORMATTED_INSPECTION_DATE) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) AS MR_INSPECTION_DATE,
        LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) AS MR_INSPECTION_COST,
        (LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) - COST_OF_INSPECTION_IN_DOLLARS) AS CHANGE_IN_COST,
        ((LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY FORMATTED_INSPECTION_DATE DESC) - COST_OF_INSPECTION_IN_DOLLARS) / COST_OF_INSPECTION_IN_DOLLARS) * 100 AS PERCENT_CHANGE_IN_COST
    FROM 
        Publishing_House
) AS cost_changes
WHERE CHANGE_IN_COST > 0;

SELECT * FROM Increased_Inspection_Costs LIMIT 5;
