-- Create database 
CREATE DATABASE IF NOT EXISTS housing_inspection;

-- Use the database
USE housing_inspection;

-- Create table with appropriate columns
CREATE TABLE public_housing_inspection_data (
    INSPECTION_ID VARCHAR(50),
    PUBLIC_HOUSING_AGENCY_NAME VARCHAR(255),
    COST_OF_INSPECTION_IN_DOLLARS DECIMAL(10,2),
    INSPECTED_DEVELOPMENT_NAME VARCHAR(255),
    INSPECTED_DEVELOPMENT_ADDRESS VARCHAR(255),
    INSPECTED_DEVELOPMENT_CITY VARCHAR(100),
    INSPECTED_DEVELOPMENT_STATE VARCHAR(2),
    INSPECTION_DATE VARCHAR(50),
    INSPECTION_SCORE INT
);

SELECT INSPECTION_DATE 
FROM public_housing_inspection_data 
LIMIT 5;


SET SQL_SAFE_UPDATES = 0;

-- Then run our update
UPDATE public_housing_inspection_data
SET INSPECTION_DATE = STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y');

-- Re-enable safe mode
SET SQL_SAFE_UPDATES = 1;

-- Then alter the column type
ALTER TABLE public_housing_inspection_data
MODIFY COLUMN INSPECTION_DATE DATE;

-- script for cost increase analysis
WITH RankedInspections AS (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME as PHA_NAME,
        INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS,
        LAG(INSPECTION_DATE) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE DESC) as PREV_INSPECTION_DATE,
        LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE DESC) as PREV_INSPECTION_COST,
        COUNT(*) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME) as inspection_count
    FROM public_housing_inspection_data
)
SELECT DISTINCT
    PHA_NAME,
    INSPECTION_DATE as MR_INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS as MR_INSPECTION_COST,
    PREV_INSPECTION_DATE as SECOND_MR_INSPECTION_DATE,
    PREV_INSPECTION_COST as SECOND_MR_INSPECTION_COST,
    (COST_OF_INSPECTION_IN_DOLLARS - PREV_INSPECTION_COST) as CHANGE_IN_COST,
    ROUND(((COST_OF_INSPECTION_IN_DOLLARS - PREV_INSPECTION_COST) / PREV_INSPECTION_COST * 100), 2) as PERCENT_CHANGE_IN_COST
FROM RankedInspections
WHERE PREV_INSPECTION_COST IS NOT NULL
    AND COST_OF_INSPECTION_IN_DOLLARS > PREV_INSPECTION_COST
    AND inspection_count > 1
ORDER BY PERCENT_CHANGE_IN_COST DESC;







