USE aly6030;

DROP TABLE IF EXISTS `public_housing_inspection_data`;

CREATE TABLE `public_housing_inspection_data` (
	`INSPECTION_ID` INT,
    `PUBLIC_HOUSING_AGENCY_NAME` TEXT,
    `COST_OF_INSPECTION_IN_DOLLARS` INT,
    `INSPECTED_DEVELOPMENT_NAME` TEXT,
    `INSPECTED_DEVELOPMENT_ADDRESS` TEXT,
    `INSPECTED_DEVELOPMENT_CITY` TEXT,
    `INSPECTED_DEVELOPMENT_STATE` TEXT,
    `INSPECTION_DATE` TEXT,
    `INSPECTION_SCORE` INT
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/public_housing_inspection_data.csv'
INTO TABLE `public_housing_inspection_data`
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

WITH CTE AS (
	SELECT 
		PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
		COST_OF_INSPECTION_IN_DOLLARS,
		STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS INSPECTION_DATE,
		LEAD(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') DESC) AS SECOND_MR_INSPECTION_DATE,
        LEAD(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') DESC) AS SECOND_MR_INSPECTION_COST,
        ROW_NUMBER() OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') DESC) AS R_NUMBER,
        COUNT(*) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME) AS COUNTS
	FROM public_housing_inspection_data
)
SELECT 
	PHA_NAME,
    INSPECTION_DATE AS MR_INSPECTION_DATE,
    COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    (COST_OF_INSPECTION_IN_DOLLARS - SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
    ROUND((COST_OF_INSPECTION_IN_DOLLARS - SECOND_MR_INSPECTION_COST)*100 / SECOND_MR_INSPECTION_COST, 2) AS PERCENT_CHANGE_IN_COST
FROM CTE
WHERE COUNTS >= 2 AND R_NUMBER = 1 AND (COST_OF_INSPECTION_IN_DOLLARS - SECOND_MR_INSPECTION_COST) > 0 
INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Zilu_Ji_Assignment3.csv'
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
;
