WITH ordered_inspections AS (
    SELECT
        PUBLIC_HOUSING_AGENCY_NAME,
        INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS,
        LAG(INSPECTION_DATE) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE,
        LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST
    FROM public_housing_inspection_data
),

inspection_differences AS (
    SELECT
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        INSPECTION_DATE AS MR_INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS AS MR_INSPECTION_COST,
        SECOND_MR_INSPECTION_DATE,
        SECOND_MR_INSPECTION_COST,
        (COST_OF_INSPECTION_IN_DOLLARS - SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
        ROUND(((COST_OF_INSPECTION_IN_DOLLARS - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST) * 100, 2) AS PERCENT_CHANGE_IN_COST
    FROM ordered_inspections
)

SELECT
    PHA_NAME,
    MR_INSPECTION_DATE,
    MR_INSPECTION_COST,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    CHANGE_IN_COST,
    PERCENT_CHANGE_IN_COST
FROM inspection_differences
WHERE
    SECOND_MR_INSPECTION_COST IS NOT NULL
    AND CHANGE_IN_COST > 0;
