SELECT 
    PH1.PHA_NAME,
    PH1.INSPECTION_DATE AS MR_INSPECTION_DATE,
    PH1.INSPECTION_COST AS MR_INSPECTION_COST,
    PH1.SECOND_MR_INSPECTION_DATE,
    PH1.SECOND_MR_INSPECTION_COST,
    (PH1.INSPECTION_COST - PH1.SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
    ROUND(((PH1.INSPECTION_COST - PH1.SECOND_MR_INSPECTION_COST) / PH1.SECOND_MR_INSPECTION_COST) * 100, 2) AS PERCENT_CHANGE_IN_COST
FROM (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        CAST(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS DATE) AS INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS AS INSPECTION_COST,
        LAG(CAST(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS DATE)) 
            OVER (
                PARTITION BY PUBLIC_HOUSING_AGENCY_NAME 
                ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') DESC
            ) AS SECOND_MR_INSPECTION_DATE,
        LAG(COST_OF_INSPECTION_IN_DOLLARS) 
            OVER (
                PARTITION BY PUBLIC_HOUSING_AGENCY_NAME 
                ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') DESC
            ) AS SECOND_MR_INSPECTION_COST
    FROM public_housing_inspection_data
) AS PH1
JOIN (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        MAX(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) AS LatestInspectionDate
    FROM public_housing_inspection_data
    GROUP BY PUBLIC_HOUSING_AGENCY_NAME
) AS PH2 
ON PH1.PHA_NAME = PH2.PHA_NAME AND PH1.INSPECTION_DATE = PH2.LatestInspectionDate
WHERE PH1.SECOND_MR_INSPECTION_COST IS NOT NULL
AND PH1.INSPECTION_COST > PH1.SECOND_MR_INSPECTION_COST;
