SELECT 
    PHA_NAME,
    INSPECTION_DATE AS MR_INSPECTION_DATE,
    INSPECTION_COST AS MR_INSPECTION_COST,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    (INSPECTION_COST - SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
    ROUND(((INSPECTION_COST - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST) * 100, 2) AS PERCENT_CHANGE_IN_COST
FROM (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME as PHA_NAME,
        INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS as INSPECTION_COST,
        LAG(INSPECTION_DATE) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE,
        LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST
    FROM 6030A3.public_housing_inspection_data
) AS InspectionRanked
WHERE 
    SECOND_MR_INSPECTION_COST IS NOT NULL
    AND INSPECTION_COST > SECOND_MR_INSPECTION_COST
ORDER BY PHA_NAME;

