use public_housing_inspection;
# looking at the type of data
DESCRIBE public_housing_inspection_data;


SELECT
    PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
    COUNT(*) AS total_inspections
FROM
    public_housing_inspection_data
GROUP BY
    PUBLIC_HOUSING_AGENCY_NAME
HAVING
    total_inspections > 1
ORDER BY
    total_inspections DESC;


WITH inspection_costs AS (
    SELECT
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS AS INSPECTION_COST
    FROM
        public_housing_inspection_data
)
SELECT
    PHA_NAME,
    INSPECTION_DATE,
    INSPECTION_COST,
    LEAD(INSPECTION_DATE) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE,
    LEAD(INSPECTION_COST) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST
FROM
    inspection_costs
ORDER BY
    PHA_NAME, INSPECTION_DATE DESC
LIMIT 0, 1000;


WITH inspection_costs AS (
    SELECT
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS AS INSPECTION_COST
    FROM
        public_housing_inspection_data
),
inspection_changes AS (
    SELECT
        PHA_NAME,
        INSPECTION_DATE,
        INSPECTION_COST,
        LEAD(INSPECTION_DATE) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE,
        LEAD(INSPECTION_COST) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST
    FROM
        inspection_costs
)
SELECT
    PHA_NAME,
    INSPECTION_DATE AS MR_INSPECTION_DATE,
    INSPECTION_COST AS MR_INSPECTION_COST,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    (INSPECTION_COST - SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
    ((INSPECTION_COST - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST) * 100 AS PERCENT_CHANGE_IN_COST
FROM
    inspection_changes
WHERE
    SECOND_MR_INSPECTION_COST IS NOT NULL
    AND INSPECTION_COST > SECOND_MR_INSPECTION_COST
ORDER BY
    PHA_NAME
LIMIT 0, 1000;
