WITH parsed_data AS (
	SELECT 
		PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
		DATE_FORMAT(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y'), '%Y-%m-%d') AS INSPECTION_DATE, -- convert dates from TEXT to Date format 
		COST_OF_INSPECTION_IN_DOLLARS AS INSPECTION_COST
	FROM public_housing_inspection_data
), ranked_data AS (
	SELECT 
		*,
		ROW_NUMBER() OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS row_num,
		LEAD(INSPECTION_DATE, 1) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_DATE, -- to show previous development inspection date
		LEAD(INSPECTION_COST, 1) OVER (PARTITION BY PHA_NAME ORDER BY INSPECTION_DATE DESC) AS SECOND_MR_INSPECTION_COST -- to show previous development inspection cost
	FROM parsed_data
), final AS (
	SELECT
		PHA_NAME,
		INSPECTION_DATE AS MR_INSPECTION_DATE,
		INSPECTION_COST AS MR_INSPECTION_COST,
		SECOND_MR_INSPECTION_DATE,
		SECOND_MR_INSPECTION_COST,
		(INSPECTION_COST - SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
		ROUND((INSPECTION_COST - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST * 100, 2) AS PERCENT_CHANGE_IN_COST
	FROM ranked_data
	WHERE row_num = 1
	AND SECOND_MR_INSPECTION_COST IS NOT NULL -- to filter out PHAs that only performed one inspection
	AND INSPECTION_COST > SECOND_MR_INSPECTION_COST -- to filter only those PHAs that saw an increase in cost
)
SELECT *
FROM final;
