USE PHA;
-- Adjust the format to match the data
SET SQL_SAFE_UPDATES = 0;

UPDATE public_housing_inspection_data
SET INSPECTION_DATE = STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y');

SET SQL_SAFE_UPDATES = 1; 
-- Filter Data for PHAs with Multiple Inspections
CREATE TEMPORARY TABLE pha_multiple_inspections AS
SELECT PUBLIC_HOUSING_AGENCY_NAME
FROM public_housing_inspection_data
GROUP BY PUBLIC_HOUSING_AGENCY_NAME
HAVING COUNT(*) > 1;

-- Apply Lead/Lag Function
WITH inspection_ranked AS (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME,
        INSPECTION_DATE,
        COST_OF_INSPECTION_IN_DOLLARS,
        ROW_NUMBER() OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY INSPECTION_DATE DESC) AS row_rank
    FROM public_housing_inspection_data
    WHERE PUBLIC_HOUSING_AGENCY_NAME IN (SELECT PUBLIC_HOUSING_AGENCY_NAME FROM pha_multiple_inspections)
),
lead_lag_calculated AS (
    SELECT 
        PUBLIC_HOUSING_AGENCY_NAME,
        MAX(CASE WHEN row_rank = 1 THEN INSPECTION_DATE END) AS MR_INSPECTION_DATE,
        MAX(CASE WHEN row_rank = 1 THEN COST_OF_INSPECTION_IN_DOLLARS END) AS MR_INSPECTION_COST,
        MAX(CASE WHEN row_rank = 2 THEN INSPECTION_DATE END) AS SECOND_MR_INSPECTION_DATE,
        MAX(CASE WHEN row_rank = 2 THEN COST_OF_INSPECTION_IN_DOLLARS END) AS SECOND_MR_INSPECTION_COST
    FROM inspection_ranked
    GROUP BY PUBLIC_HOUSING_AGENCY_NAME
)
SELECT *,
       (MR_INSPECTION_COST - SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
       ((MR_INSPECTION_COST - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST) * 100 AS PERCENT_CHANGE_IN_COST
FROM lead_lag_calculated
WHERE MR_INSPECTION_COST > SECOND_MR_INSPECTION_COST;
