DROP DATABASE IF EXISTS `ALY6030_Assignment3_Xiaohan`;
CREATE DATABASE IF NOT EXISTS `ALY6030_Assignment3_Xiaohan`;
Use `ALY6030_Assignment3_Xiaohan`;
SET GLOBAL local_infile = 1;

-- Create Table
CREATE TABLE public_housing_inspection (
    INSPECTION_ID INT PRIMARY KEY,
    PUBLIC_HOUSING_AGENCY_NAME VARCHAR(255),
    COST_OF_INSPECTION_IN_DOLLARS DECIMAL(10, 2),
    INSPECTED_DEVELOPMENT_NAME VARCHAR(255),
    INSPECTED_DEVELOPMENT_ADDRESS VARCHAR(255),
    INSPECTED_DEVELOPMENT_CITY VARCHAR(100),
    INSPECTED_DEVELOPMENT_STATE CHAR(2),
    INSPECTION_DATE DATE,
    INSPECTION_SCORE INT
);

-- Load Data into the Table
LOAD DATA LOCAL INFILE 'Users/sherry_yu/ALY6030/MOD5/public_housing_inspection_data_2.csv'
INTO TABLE public_housing_inspection
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(INSPECTION_ID, PUBLIC_HOUSING_AGENCY_NAME, COST_OF_INSPECTION_IN_DOLLARS, 
 INSPECTED_DEVELOPMENT_NAME, INSPECTED_DEVELOPMENT_ADDRESS, 
 INSPECTED_DEVELOPMENT_CITY, INSPECTED_DEVELOPMENT_STATE, 
 @INSPECTION_DATE, INSPECTION_SCORE)
SET INSPECTION_DATE = STR_TO_DATE(@INSPECTION_DATE, '%m/%d/%Y');

--    --
-- Q3 --
--    --

-- CREATE TABLE TransactionFactTable
CREATE TABLE `TransactionFactTable` (
    INSPECTION_ID INT PRIMARY KEY,
    PUBLIC_HOUSING_AGENCY_NAME VARCHAR(100),
    COST_OF_INSPECTION_IN_DOLLARS INT,
    INSPECTED_DEVELOPMENT_NAME VARCHAR(100),
    INSPECTED_DEVELOPMENT_ADDRESS VARCHAR(100),
    INSPECTED_DEVELOPMENT_CITY VARCHAR(100),
    INSPECTED_DEVELOPMENT_STATE VARCHAR(10),
    INSPECTION_DATE DATE,
    INSPECTION_SCORE INT
);
-- CREATE TABLE PeriodicSnapshotFactTable
CREATE TABLE `PeriodicSnapshotFactTable` (
    PUBLIC_HOUSING_AGENCY_NAME VARCHAR(100) PRIMARY KEY ,
    SNAPSHOT_DATE DATE,
    TOTAL_COST_OF_INSPECTIONS_IN_DOLLARS INT
);

-- Insert info TransactionFactTable
LOAD DATA LOCAL INFILE '/Users/sherry_yu/ALY6030/MOD5/public_housing_inspection_data_2.csv'
 INTO TABLE `TransactionFactTable`
 FIELDS TERMINATED BY ',' 
 LINES TERMINATED BY '\n' 
 IGNORE 1 LINES
    (INSPECTION_ID,
    PUBLIC_HOUSING_AGENCY_NAME, 
    COST_OF_INSPECTION_IN_DOLLARS,
    INSPECTED_DEVELOPMENT_NAME ,
    INSPECTED_DEVELOPMENT_ADDRESS, 
    INSPECTED_DEVELOPMENT_CITY, 
    INSPECTED_DEVELOPMENT_STATE,
    @INSPECTION_DATE, INSPECTION_SCORE)
    SET INSPECTION_DATE = STR_TO_DATE(@INSPECTION_DATE, '%m/%d/%Y');
 
 SELECT * FROM `TransactionFactTable` LIMIT 5;
 
-- Insert info into PeriodicSnapshotFactTable
INSERT IGNORE INTO `PeriodicSnapshotFactTable` 
(PUBLIC_HOUSING_AGENCY_NAME, SNAPSHOT_DATE, 
TOTAL_COST_OF_INSPECTIONS_IN_DOLLARS)
SELECT
    PUBLIC_HOUSING_AGENCY_NAME,
    DATE_FORMAT(INSPECTION_DATE, '%Y-%m-01') AS SNAPSHOT_DATE,
    SUM(COST_OF_INSPECTION_IN_DOLLARS) AS TOTAL_COST_OF_INSPECTIONS_IN_DOLLARS
FROM
    `TransactionFactTable`
GROUP BY
    PUBLIC_HOUSING_AGENCY_NAME, SNAPSHOT_DATE
ORDER BY
    PUBLIC_HOUSING_AGENCY_NAME, SNAPSHOT_DATE;
    
SELECT * FROM `PeriodicSnapshotFactTable` LIMIT 5;

--    --
-- Q5 --
--    --

-- Rank Inspections and Calculate Previous Inspection Data
WITH InspectionRanked AS (
    SELECT PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
           INSPECTION_DATE, COST_OF_INSPECTION_IN_DOLLARS AS INSPECTION_COST,
           LAG(INSPECTION_DATE) OVER (
               PARTITION BY PUBLIC_HOUSING_AGENCY_NAME 
               ORDER BY INSPECTION_DATE) 
               AS SECOND_MR_INSPECTION_DATE,
           LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (
               PARTITION BY PUBLIC_HOUSING_AGENCY_NAME 
               ORDER BY INSPECTION_DATE) 
               AS SECOND_MR_INSPECTION_COST,
           ROW_NUMBER() OVER (
           PARTITION BY PUBLIC_HOUSING_AGENCY_NAME 
           ORDER BY INSPECTION_DATE DESC) 
           AS RN
    FROM public_housing_inspection
)
-- Retrieve data from the CTE InspectionRanked with the specified conditions
SELECT 
    PHA_NAME,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    INSPECTION_DATE AS MR_INSPECTION_DATE,
    INSPECTION_COST AS MR_INSPECTION_COST,
    (INSPECTION_COST - SECOND_MR_INSPECTION_COST) AS CHANGE_IN_COST,
    ROUND((INSPECTION_COST - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST * 100, 2) AS PERCENT_CHANGE_IN_COST
FROM InspectionRanked
WHERE SECOND_MR_INSPECTION_COST IS NOT NULL
AND INSPECTION_COST > SECOND_MR_INSPECTION_COST
-- Only the most recent inspection record
AND RN = 1; 