WITH Inspection_CTE AS (
    SELECT
        PUBLIC_HOUSING_AGENCY_NAME AS PHA_NAME,
        STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y') AS INSPECTION_DATE,  -- Convert date format if needed
        COST_OF_INSPECTION_IN_DOLLARS AS INSPECTION_COST,
        LAG(STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) AS SECOND_MR_INSPECTION_DATE,
		LAG(COST_OF_INSPECTION_IN_DOLLARS) OVER (PARTITION BY PUBLIC_HOUSING_AGENCY_NAME ORDER BY STR_TO_DATE(INSPECTION_DATE, '%m/%d/%Y')) AS SECOND_MR_INSPECTION_COST
	FROM `assignment 3`.`public_housing_inspection_data`
)


SELECT
    PHA_NAME,
    INSPECTION_DATE AS MR_INSPECTION_DATE,
    INSPECTION_COST AS MR_INSPECTION_COST,
    SECOND_MR_INSPECTION_DATE,
    SECOND_MR_INSPECTION_COST,
    INSPECTION_COST - SECOND_MR_INSPECTION_COST AS CHANGE_IN_COST,
    ROUND(((INSPECTION_COST - SECOND_MR_INSPECTION_COST) / SECOND_MR_INSPECTION_COST) * 100, 2) AS PERCENT_CHANGE_IN_COST
FROM Inspection_CTE
WHERE SECOND_MR_INSPECTION_COST IS NOT NULL
  AND INSPECTION_COST > SECOND_MR_INSPECTION_COST
ORDER BY PHA_NAME, MR_INSPECTION_DATE;